import Header from "@/components/header";
import type { Metadata } from "next";
import { Coda, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import IconChat from "@/components/chat-bot/icon-chat";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const coda = Coda({
  variable: "--font-coda",
  subsets: ["latin"],
  weight: ["400", "800"],
});
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${coda.variable} antialiased`}
      >
        <Header />
        {children}
        <IconChat />
      </body>
    </html>
  );
}
